version: "3.8"
services:
  etl_worker:
    image: fajarherdian22/etl-prefect-flow:latest
    environment:
      - PREFECT_API_URL=http://<your-server-ip>:4200/api
    command: prefect worker start -p docker-pool
